/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mlproject.fuzzy.gui;

import java.awt.Color;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import mlproject.fuzzy.FuzzyRule;
import mlproject.fuzzy.FuzzySystem;

/**
 *
 * @author samyn_000
 */
public class FuzzyRulePanel extends javax.swing.JPanel implements ActionListener{
    private FuzzySystem fuzzySystem;
    
    /**
     * Creates new form FuzzyRulePanel
     */
    public FuzzyRulePanel() {
        initComponents();
        
        Timer t = new Timer(50, this);
        t.setInitialDelay(100);
        t.start();
    }
    
    
    public void setFuzzySystem(FuzzySystem fuzzySystem){
        this.fuzzySystem = fuzzySystem;
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(fuzzySystem == null){
            return;
        }
        
        int y = 40;
        FontMetrics fm = g.getFontMetrics();
        if ( fuzzySystem.getNrOfRules() == 0 )
            System.out.println("wrong number of rules");
        for( FuzzyRule rule: fuzzySystem.getRules())
        {
            float currentResult = rule.getCurrentResult();
            String r = rule.getRuleText();
            //System.out.println("result : " + currentResult);
            g.setColor(Color.GREEN);
            g.fillRoundRect(10,y, (int)(currentResult*100),fm.getHeight(),3,3);
            g.setColor(Color.BLACK);
            g.drawRoundRect(10,y, 100, fm.getHeight(), 3,3);
            
            g.drawString(r,120,y+fm.getAscent());
            
            y+= fm.getHeight()+5;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Fuzzy Rules"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //System.out.println("repainting");
       repaint();
    }
}
