/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewOkCancelDialog.java
 *
 * Created on Dec 8, 2011, 11:59:23 AM
 */
package mlproject.fuzzy.gui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileFilter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import mlproject.fuzzy.FuzzySystem;
import mlproject.fuzzy.FuzzyVariable;

/**
 *
 * @author Koen
 */
public class FuzzySystemDialog extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form NewOkCancelDialog */
    public FuzzySystemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    public void setFuzzySystem(FuzzySystem system){
        this.fuzzySystemUI1.setFuzzySystem(system);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        fuzzySystemUI1 = new mlproject.fuzzy.gui.FuzzySystemUI();
        btnExport = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        btnExport.setText("Export ...");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addComponent(fuzzySystemUI1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(fuzzySystemUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton)
                    .addComponent(btnExport))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
         BufferedWriter bw = null;
        try {
            // TODO add your handling code here:
            String currentDir = System.getProperty("user.dir");
            File subdir = new File(currentDir, "responses");
            if (!subdir.exists()) {
                subdir.mkdir();
            }
            File[] existing = subdir.listFiles(new FileFilter() {

                @Override
                public boolean accept(File pathname) {
                    return (pathname.getPath().toLowerCase().endsWith(".res"));
                }
            });
            int maxNumber = 0;
            for (File file : existing) {
                String path = file.getPath();
                int startIndex = path.indexOf('_') + 1;
                int endIndex = path.lastIndexOf('.');
                int number = Integer.parseInt(path.substring(startIndex, endIndex));
                if (number > maxNumber) {
                    maxNumber = number;
                }
            }
            File saveFile = new File(subdir, "response_" + (maxNumber + 1) + ".res");
            bw = new BufferedWriter(new FileWriter(saveFile));
            
            FuzzySystem system = this.fuzzySystemUI1.getFuzzySystem();
            
            int inputs = system.getNrOfInputs();
         
            FuzzyVariable[] inputVars  =new FuzzyVariable[inputs];
            FuzzyVariable[] outputVars  = new FuzzyVariable[1];
            
            int index = 0;
            for (FuzzyVariable input : system.getInputs()) {
                inputVars[index] = input;
                ++index;
            }
            
            for (FuzzyVariable output : system.getOutputs()){
                outputVars[0] = output;
            }
            
            int size = 50;
            
            bw.write("# name: fuzzysystem");
            bw.write("\n# type: matrix");
            bw.write("\n# rows: ");
            bw.write(Integer.toString(size));
            bw.write("\n# columns: ");
            bw.write(Integer.toString(size));
            bw.write("\n");
            if (inputs == 1) {
                /*
                int index = 0;
                for (FuzzyVariable cell: system.getInputs()) {
                    inputVars[index]=cell;
                    bw.write(cell.getName());
                    ++index;
                }
                bw.write(";");
                bw.write("output\n");
                 */
                for (int i = 0; i < size; ++i) {
                    for (int celli = 0; celli < inputs; ++celli) {
                        
                        FuzzyVariable cell = inputVars[i];
                        float value = cell.getMinimum() + (cell.getMaximum() - cell.getMinimum()) * i * (1.0f/ size);
                        cell.setCurrentValue(value);
                        bw.write(Float.toString(value));
                        bw.write(" ");
                    }
                    system.evaluate();
                    bw.write(Float.toString(outputVars[0].getOutputValue()));
                    bw.write("\n");
                }
            } else if (inputs == 2) {
                /*
                FuzzyVariable d1_cell = inputVars[1];
                bw.write(" 0");
                for (int d1 = 0; d1 < 100; ++d1) {
                    float d1_input = d1_cell.getMinimum() + (d1_cell.getMaximum() - d1_cell.getMinimum()) * d1 / 100.0f;
                    bw.write(";");
                    bw.write(Float.toString(d1_input));
                }
                bw.write("\n");
                 */

                for (int d1 = 0; d1 < size; ++d1) {
                    FuzzyVariable cell = inputVars[0];
                    float value = cell.getMinimum() + (cell.getMaximum() - cell.getMinimum()) * d1 *(1.0f/ size);
                    cell.setCurrentValue(value);

                    for (int d2 = 0; d2 < size; ++d2) {
                        FuzzyVariable cell2 = inputVars[1];
                        float value2 = cell2.getMinimum() + (cell2.getMaximum() - cell2.getMinimum()) * d2 *(1.0f/ size);
                        cell2.setCurrentValue(value2);

                        system.evaluate(false);
                        
                        bw.write(Float.toString(outputVars[0].getOutputValue()));
                        bw.write(" ");
                    }
                    if (d1 != size-1) {
                        bw.write("\n");
                    }
                }
            }
            bw.close();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                bw.close();
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuzzySystemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuzzySystemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuzzySystemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuzzySystemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FuzzySystemDialog dialog = new FuzzySystemDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton cancelButton;
    private mlproject.fuzzy.gui.FuzzySystemUI fuzzySystemUI1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
