/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StoredAnimationPanel.java
 *
 * Created on Dec 18, 2011, 3:13:50 PM
 */
package mlproject.animation;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Koen
 */
public class StoredAnimationPanel extends javax.swing.JPanel {
    private StyleLearner learner;
    private JFileChooser chooser = new JFileChooser();
    
    private Bone upperArmBone;
    private Bone lowerArmBone;
    private Bone handBone;
    
    /** Creates new form StoredAnimationPanel */
    public StoredAnimationPanel() {
        initComponents();
        chooser.setFileFilter(new FileFilter(){

            @Override
            public boolean accept(File f) {
                return  f.isDirectory() || f.getPath().endsWith(".mo");
            }

            @Override
            public String getDescription() {
               return "motion capture files";
            }
            
        });
        chooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        chooser.setMultiSelectionEnabled(true);
    }
    
     /**
     * @return the upperArmBone
     */
    public Bone getUpperArmBone() {
        return upperArmBone;
    }

    /**
     * @param upperArmBone the upperArmBone to set
     */
    public void setUpperArmBone(Bone upperArmBone) {
        this.upperArmBone = upperArmBone;
    }

    /**
     * @return the lowerArmBone
     */
    public Bone getLowerArmBone() {
        return lowerArmBone;
    }

    /**
     * @param lowerArmBone the lowerArmBone to set
     */
    public void setLowerArmBone(Bone lowerArmBone) {
        this.lowerArmBone = lowerArmBone;
    }

    /**
     * @return the handBone
     */
    public Bone getHandBone() {
        return handBone;
    }

    /**
     * @param handBone the handBone to set
     */
    public void setHandBone(Bone handBone) {
        this.handBone = handBone;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnimationFile = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        btnLoadFile = new javax.swing.JButton();
        btnStartLearning = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(220, 300));

        lblAnimationFile.setText("Load animation : ");

        btnLoadFile.setText("...");
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFileActionPerformed(evt);
            }
        });

        btnStartLearning.setText("Start hand Learning");
        btnStartLearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartLearningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoadFile)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnimationFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addComponent(btnStartLearning))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimationFile)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoadFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(btnStartLearning)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        // TODO add your handling code here:
        
        int result = chooser.showOpenDialog(this);
        if ( result == JFileChooser.APPROVE_OPTION){
            File[] selectedFiles = chooser.getSelectedFiles();
            learner = new StyleLearner(selectedFiles);
            txtFileName.setText("loaded");
        }
    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void btnStartLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartLearningActionPerformed
        // TODO add your handling code here:
        if (learner != null)
            learner.adaptNeuralNet("hand", getHandBone().getNeuralController());
    }//GEN-LAST:event_btnStartLearningActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnStartLearning;
    private javax.swing.JLabel lblAnimationFile;
    private javax.swing.JTextField txtFileName;
    // End of variables declaration//GEN-END:variables
}
